name: kcard
description: Personal Finance Tracker App.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  fpdart: ^1.1.0
  shared_preferences: ^2.2.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  google_nav_bar: ^5.0.6
  contained_tab_bar_view: ^0.8.0
  buttons_tabbar: ^1.3.7+1
  gap: ^3.0.1
  get: ^4.6.6
  grouped_list: ^5.1.2
  fl_chart: ^0.63.0
  auto_size_text: ^3.0.0
  zoom_tap_animation: ^1.1.0
  introduction_screen: ^3.1.11
  omni_datetime_picker: ^1.0.9
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  icons_plus: ^4.0.0
  gif: ^2.2.0
  cool_dropdown: ^2.1.0
  loading_animation_widget: ^1.2.0+4
  toggle_switch: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey/Marhey-VariableFont_wght.ttf
        - asset: assets/fonts/Marhey/static/Marhey-Bold.ttf
        - asset: assets/fonts/Marhey/static/Marhey-Light.ttf
        - asset: assets/fonts/Marhey/static/Marhey-Medium.ttf
        - asset: assets/fonts/Marhey/static/Marhey-Regular.ttf
        - asset: assets/fonts/Marhey/static/Marhey-SemiBold.ttf

    - family: Aref_Ruqaa_Ink
      fonts:
        - asset: assets/fonts/Aref_Ruqaa_Ink/ArefRuqaaInk-Bold.ttf
        - asset: assets/fonts/Aref_Ruqaa_Ink/ArefRuqaaInk-Regular.ttf